# Generated by Django 3.2.13 on 2022-04-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='district',
            name='state',
        ),
        migrations.AddField(
            model_name='state',
            name='district',
            field=models.ManyToManyField(to='demo.District'),
        ),
    ]
